### ISSUE TITLE
Iterators are not bidirectional

### ISSUE THREAD

**Issue by JohelEGP** [timniederhausen/rapidxml#1]
Greetings, Tim.

I want to let you know that fee8dbd and 0f6c8a1 introduced a number of changes to the iterators that prevent them from satisfying the requirements of [`BidirectionalIterator`](http://en.cppreference.com/w/cpp/concept/BidirectionalIterator), which they claim to be via their `iterator_category` member alias. Now they are `InputIterator`s at best.

**Comment by timniederhausen** [comment]
Thanks for letting me know, it should be fixed now.

Some of the more serious issues seem to have been present in the original version as well (operator--(int) actually incremented the iterator).
