### ISSUE TITLE
SAX interface

### ISSUE THREAD

**Issue by silviucpp** [timniederhausen/rapidxml#2]
Hello,

Some projects contains also an interface for SAX parser: https://github.com/halx99/xmldrv3/blob/master/xmldrv3/rapidxml/rapidxml_sax3.hpp

Will be nice to integrate also this one
Silviu

**Comment by timniederhausen** [comment]
Hi,

the SAX parser you linked to looks like a copy of rapidxml's parsing code, with callbacks added. Duplicating the entire parser code (for the DOM and SAX version) seems like a maintenance nightmare to me.

I'd prefer to have a generic parser that is then used by the DOM and SAX interface, but that's quite a bit of work, which I unfortunately don't have the time for. If you really needs this, then I'm afraid you'll need to work on this yourself, sorry.
