### ISSUE TITLE
 Issue in Parsing big files 

### ISSUE THREAD

**Issue by dheeraj12190** [timniederhausen/rapidxml#4]
Hi,
I am using rapidxml in my project. it is working fine with small files but once the file size increases more then 65KB then searching first node gives segmentation fault error

**Comment by timniederhausen** [comment]
Hi,
can you provide an example file?
I use rapidxml to parse XML files several MB in size, so it's definitely working for me.

**Comment by dheeraj12190** [comment]
[2.txt](https://github.com/timniederhausen/rapidxml/files/2403883/2.txt)
Hi 
Thank you for your prompt response.  
I have attached the file for your reference. I am changing extension from xml to txt. please check.

**Comment by timniederhausen** [comment]
Hi,
can you show me how you're loading/parsing this file?

I just wrote a simple test that outputs a tree-like representation of it:
```
#include "../test_utils.hpp"
#include "../../rapidxml_utils.hpp"

void print_nodes(rapidxml::xml_node<char>* node, int ident = 0)
{
    std::cout << std::string(ident, ' ');
    std::cout << std::string(node->name(), node->name_size()) << '\n';

    for (auto n = node->first_node(); n; n = n->next_sibling())
        print_nodes(n, ident + 2);
}

int main(int argc, char *argv[])
{
    if (argc < 2)
        return 2;
    rapidxml::xml_document<char> doc;
    try {
        file<char> xml(argv[1]);
        doc.parse<0>(xml.data());
        print_nodes(&doc);
    } catch (std::exception& e) {
        std::cout << "Failed to parse file " << argv[1] << ": " << e.what() << '\n';
        return 1;
    }
    return 0;
}
```
This works just fine, so it doesn't appear to be a problem in rapidxml that leads to your segmentation faults.

**Comment by dheeraj12190** [comment]
Thanks a lot for your quick support and response.
I was using all this stuff in a class. in which I have 'doc' as a class member variable and parsed the document in constructor.  where as doing this task  "node->name(), node->name_size()" in member function then it was giving segmentation fault error. now I have defines doc as local variable in my member variable functions now its working fine. 
below is my code for the reference.
class MIOSParser
{
	private:
		xml_document<char> doc;
		string sXMLFile;
	public:
		MIOSParser(string sFileName);
		int parseGeneralData(vector<MIOSInstantData> &InstantRecords);		
};  
MIOSParser::MIOSParser(string sFileName)
{
	try 
	{
		//ifstream theFile("../../inp/2.xml");
		//ifstream theFile(sFileName);

		rapidxml::file<char> xml("../../inp/2.xml");
	        doc.parse<0>(xml.data());
		cout << endl << "Size of Buffer:" << buffer.size() << endl;
		sXMLFile = sFileName;
	}
	catch (exception &e)
	{
		cout << endl << "Exception Occured:" << e.what();
	}
}
int MIOSParser::parseGeneralData(vector<MIOSInstantData> &InstantRecords)
{
	xml_node<> * root_node;
	MIOSInstantData tempRecord;
	try 
	{
		//rapidxml::file<char> xml(sXMLFile.c_str());//"../../inp/2.xml");
		//doc.parse<0>(xml.data());

		cout << endl << "test1" << endl;
		root_node = doc.first_node("cdf",0,false);
		if (root_node == NULL)
		{	
			cout << endl << "Node Not Found" << endl;
			return 0;
		}
		else
		{
			cout << endl << "Node Found" << endl;
			//return 1;
		}
		for (xml_node<> *utility_type = root_node->first_node("UTILITYTYPE");utility_type;utility_type = utility_type->next_sibling())
		{
			string s = utility_type->first_attribute("CODE")->value();
			cout << endl << "Value:" << s;
			for (xml_node<> *DataType = utility_type->first_node();DataType;DataType = DataType->next_sibling())
			{
				//cout << endl << "TagName:" << DataType->name();
				string tag = DataType->name();
				if (tag == "D1") // Parse General Data
				{
					for (xml_node<> *General = DataType->first_node();General; General = General->next_sibling())
					{
						//cout << endl << "	" << General->name() << ":" << General->value();
						tempRecord.Tag = General->name();
						tempRecord.Value = General->value();
						InstantRecords.push_back(tempRecord);
						// Pasre Attribute List
						for (xml_attribute<> *attrib = General->first_attribute();attrib;attrib = attrib->next_attribute())
						{
							//cout << endl << " " << "Attribute Name:" << attrib->name() << "	" << "Attribute Value:" << attrib->value();
							tempRecord.Tag = General->name();
							tempRecord.Value = General->value();
							InstantRecords.push_back(tempRecord);
						}
					}
				}
			}
		}
	}
	catch (exception &e)
	{
		
	}	
}

**Comment by timniederhausen** [comment]
```
	rapidxml::file<char> xml("../../inp/2.xml");
        doc.parse<0>(xml.data());
```
That's the problem. The data you pass to `parse()` must live as long as the document. In your case the file data is deleted when the `rapidxml::file` object goes out of scope.

**Comment by dheeraj12190** [comment]
Thanks. Issue Resolved
