### ISSUE TITLE
RHVoice fails to build with this fork

### ISSUE THREAD

**Issue by CyberTailor** [timniederhausen/rapidxml#5]
Full build log:
https://sysrq.in/tmp/rhvoice.build.log

[RHVoice](https://github.com/RHVoice/RHVoice) builds fine with:
a) their [bundled version](https://github.com/RHVoice/RHVoice/tree/master/src/third-party/rapidxml/rapidxml) of rapidxml
b) original rapidxml with [debian patchset](https://sources.debian.org/data/main/r/rapidxml/1.13-3/debian/patches/)

**Comment by timniederhausen** [comment]
thanks, fixed in f555b312d84485827ad28def3fc7041a0cd58209
